language: node_js
node_js:
  - "0.10"
before_install: 
  - sudo apt-get install php5
  - npm install -g grunt-cli
  - gem install sass
  - gem update --system
  - curl -sS https://getcomposer.org/installer | php
  - php composer.phar install
  - npm install grunt-phpcs
  - cp -r ./coding_standards ./vendor/squizlabs/php_codesniffer/CodeSniffer/Standards
  # xcopy "./coding_standards" "./vendor/squizlabs/php_codesniffer/CodeSniffer/Standards" /s /e /y
  - ./vendor/bin/phpcs --config-set installed_paths ../../vendor/squizlabs/php_codesniffer/CodeSniffer/Standards/Wordpress
install: npm install